language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=master
matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=master
    - python: "3.6"
      env: DJANGO=1.10
  allow_failures:
    - env: DJANGO=master
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov -e DJANGO
